import { MaterialItem, QualityTier } from '../src/types';

export const INITIAL_MATERIALS: MaterialItem[] = [
  // DOORS
  {
    id: 'mat_door_1',
    category: 'Doors',
    brand: 'Greenply',
    productName: 'Ecotec Flush Doors',
    qualityLevel: 'Economy',
    approxPrice: 2800,
    unit: 'per leaf (3x7 ft)',
    durability: '8-10 Years',
    description: 'Solid core hardwood flush door with moisture resistant resin bond.',
    recommendedUse: 'Internal Bedrooms & Utility',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_door_2',
    category: 'Doors',
    brand: 'CenturyPly',
    productName: 'Club Prime Teak Finish HDF Door',
    qualityLevel: 'Standard',
    approxPrice: 6500,
    unit: 'per leaf (3x7 ft)',
    durability: '15-20 Years',
    description: 'Boiling waterproof marine grade door with natural wood veneer face.',
    recommendedUse: 'Main Entrance & Master Suite',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_door_3',
    category: 'Doors',
    brand: 'DormaKaba / Schüco',
    productName: 'Architectural Solid Burma Teak Pivot Door',
    qualityLevel: 'Premium',
    approxPrice: 24000,
    unit: 'per leaf (4x8 ft)',
    durability: '30+ Years',
    description: 'Bespoke solid seasoned teak door with German hydraulic pivot hinges & digital lock integration.',
    recommendedUse: 'Grand Main Entry & Designer Living',
  },

  // WINDOWS
  {
    id: 'mat_win_1',
    category: 'Windows',
    brand: 'Jindal Aluminium',
    productName: 'Anodized 2-Track Sliding Windows with Mesh',
    qualityLevel: 'Economy',
    approxPrice: 320,
    unit: 'per sq.ft',
    durability: '10 Years',
    description: 'Heavy section extruded aluminum frames with 5mm clear float glass.',
    recommendedUse: 'Utility, Bathrooms & Secondary Bedrooms',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_win_2',
    category: 'Windows',
    brand: 'Fenesta',
    productName: 'UPVC Casement High-Acoustic Windows',
    qualityLevel: 'Standard',
    approxPrice: 680,
    unit: 'per sq.ft',
    durability: '20+ Years',
    description: 'Multi-chambered UPVC profiles with toughened double glazing for thermal & acoustic insulation.',
    recommendedUse: 'Living Rooms, Master Bedrooms & Front Facades',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_win_3',
    category: 'Windows',
    brand: 'Schüco / Reynaers',
    productName: 'Slimline Thermal Break Aluminium Panoramic System',
    qualityLevel: 'Premium',
    approxPrice: 1450,
    unit: 'per sq.ft',
    durability: '30+ Years',
    description: 'Minimalist sightline 20mm sliding system with motorized blinds and low-E acoustic glass.',
    recommendedUse: 'Balcony Decks, Double Height Living & Patios',
  },

  // FLOORING
  {
    id: 'mat_flr_1',
    category: 'Flooring',
    brand: 'Kajaria',
    productName: 'Ceramic Glazed Vitrified Tiles (600x600 mm)',
    qualityLevel: 'Economy',
    approxPrice: 55,
    unit: 'per sq.ft',
    durability: '12 Years',
    description: 'Nano-polished double charged vitrified tiles with stain-resistant coating.',
    recommendedUse: 'All Living, Dining, Bedrooms & Kitchen floors',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_flr_2',
    category: 'Flooring',
    brand: 'Simpolo / Somany',
    productName: 'Large Format Glazed Porcelain Slabs (1200x1800 mm)',
    qualityLevel: 'Standard',
    approxPrice: 125,
    unit: 'per sq.ft',
    durability: '20 Years',
    description: 'High-definition Italian marble replica vitrified slabs with book-matched veins.',
    recommendedUse: 'Main Foyer, Living, Dining & Master Bedroom',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_flr_3',
    category: 'Flooring',
    brand: 'RK Marble / Classic Marble',
    productName: 'Imported Statuario / Bottochino Italian Marble',
    qualityLevel: 'Premium',
    approxPrice: 420,
    unit: 'per sq.ft',
    durability: '40+ Years',
    description: 'Premium quarried Italian natural marble slab mirror-polished with epoxy treatment.',
    recommendedUse: 'Luxury Villa Living & Dining Areas',
  },

  // SANITARY
  {
    id: 'mat_san_1',
    category: 'Sanitary',
    brand: 'Cera / Hindware',
    productName: 'One-Piece Ceramic Water Closet & Vanity Basin',
    qualityLevel: 'Economy',
    approxPrice: 7500,
    unit: 'per bathroom set',
    durability: '10 Years',
    description: 'Dual flush siphon water closet with anti-bacterial glaze coating.',
    recommendedUse: 'Common Baths & Powder Rooms',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_san_2',
    category: 'Sanitary',
    brand: 'Jaquar',
    productName: 'Rimless Wall-Hung WC with Concealed Geberit Cistern',
    qualityLevel: 'Standard',
    approxPrice: 18500,
    unit: 'per bathroom set',
    durability: '15+ Years',
    description: 'Soft-closing rimless wall mounted commode with chrome flush plate & counter basin.',
    recommendedUse: 'Master Suite & Guest Bathrooms',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_san_3',
    category: 'Sanitary',
    brand: 'Kohler / Grohe',
    productName: 'Artist Editions Smart Bidet & Thermostatic Rain Shower System',
    qualityLevel: 'Premium',
    approxPrice: 65000,
    unit: 'per bathroom set',
    durability: '25+ Years',
    description: 'Heated seat intelligent bidet, digital touch flow controls & ceiling recessed 3-flow rain shower.',
    recommendedUse: 'Master Luxury Spa Bathrooms',
  },

  // PAINT
  {
    id: 'mat_pnt_1',
    category: 'Paint',
    brand: 'Tractor Emulsion (Asian Paints)',
    productName: 'Interior Smooth Matt Acrylic Emulsion',
    qualityLevel: 'Economy',
    approxPrice: 18,
    unit: 'per sq.ft (2 coats + primer)',
    durability: '4-5 Years',
    description: 'Washable interior acrylic wall paint with anti-fungal formulation.',
    recommendedUse: 'Rental Units, Utility & Ceiling Surfaces',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_pnt_2',
    category: 'Paint',
    brand: 'Asian Paints Royale',
    productName: 'Royale Luxury Sheen Emulsion with Teflon Surface Protector',
    qualityLevel: 'Standard',
    approxPrice: 38,
    unit: 'per sq.ft (2 coats + 2 putty + primer)',
    durability: '8-10 Years',
    description: 'Silky smooth finish with anti-bacterial shield and high scrub resistance.',
    recommendedUse: 'Living, Dining, Foyer & Bedrooms',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_pnt_3',
    category: 'Paint',
    brand: 'Oikos / San Marco (Italy)',
    productName: 'Stucco Veneziano & Microcement Architectural Wall Textures',
    qualityLevel: 'Premium',
    approxPrice: 165,
    unit: 'per sq.ft',
    durability: '15+ Years',
    description: 'Hand-troweled lime-based Venetian stucco plaster with mirror gloss wax polish.',
    recommendedUse: 'Feature Walls, Entrance Foyer & Staircase Voids',
  },

  // KITCHEN
  {
    id: 'mat_kit_1',
    category: 'Kitchen',
    brand: 'Local Millwork / Action TESA',
    productName: 'BWP Marine Ply Modular Counter with Laminate Finish',
    qualityLevel: 'Economy',
    approxPrice: 85000,
    unit: 'complete set (L-shape 10x8 ft)',
    durability: '8-10 Years',
    description: 'Boiling waterproof marine ply carcass with 1mm laminate shutters and stainless steel wire baskets.',
    recommendedUse: 'Standard Residential Kitchens',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_kit_2',
    category: 'Kitchen',
    brand: 'Sleek by Asian Paints / Godrej',
    productName: 'Acrylic Finish Modular Kitchen with Blum Soft-Close Hardware',
    qualityLevel: 'Standard',
    approxPrice: 195000,
    unit: 'complete set (L-shape with island)',
    durability: '15 Years',
    description: 'Anti-scratch high-gloss acrylic shutters, tandem box drawers, quartz stone countertop and built-in chimney space.',
    recommendedUse: 'Modern Open-Concept Cooking Spaces',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_kit_3',
    category: 'Kitchen',
    brand: 'Häcker / Veneta Cucine',
    productName: 'German PU Lacquer Smart Kitchen with Ceramic Countertops',
    qualityLevel: 'Premium',
    approxPrice: 620000,
    unit: 'complete designer suite',
    durability: '25+ Years',
    description: 'Handleless laser-edged PU lacquer cabinets, 12mm sintered stone island with induction integration & Blum servo-drive motorized drawers.',
    recommendedUse: 'Luxury Villa Gourmet Kitchens',
  },

  // ELECTRICAL
  {
    id: 'mat_ele_1',
    category: 'Electrical',
    brand: 'Anchor by Panasonic',
    productName: 'Penta Modular Switches & FR Copper Wiring',
    qualityLevel: 'Economy',
    approxPrice: 140,
    unit: 'per electrical point',
    durability: '10 Years',
    description: 'Flame retardant electrolytic copper cables with polycarbonate modular switch plates.',
    recommendedUse: 'Standard Home Wiring & Circuits',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_ele_2',
    category: 'Electrical',
    brand: 'Havells / Legrand',
    productName: 'Arteor / Britzy Modular Grid with Smart Home Conduit',
    qualityLevel: 'Standard',
    approxPrice: 280,
    unit: 'per electrical point',
    durability: '18 Years',
    description: 'Silver-plated contacts with surge suppression, USB-C wall outlets and dedicated Wi-Fi smart switch integration.',
    recommendedUse: 'Whole-house Intelligent Wiring',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_ele_3',
    category: 'Electrical',
    brand: 'Schneider Electric / Lutron',
    productName: 'Unica KNX Architectural Automation & Glass Touch Panels',
    qualityLevel: 'Premium',
    approxPrice: 850,
    unit: 'per electrical point',
    durability: '25+ Years',
    description: 'Full KNX home automation with capacitive glass keypads, motorized curtain controllers and scene dimming.',
    recommendedUse: 'Smart Luxury Residential Automation',
  },

  // PLUMBING
  {
    id: 'mat_plm_1',
    category: 'Plumbing',
    brand: 'Supreme',
    productName: 'CPVC Lifeline & SWR Drainage Pipes',
    qualityLevel: 'Economy',
    approxPrice: 45,
    unit: 'per running ft',
    durability: '15 Years',
    description: 'NSF certified chlorine-resistant CPVC hot/cold lines with solvent weld joints.',
    recommendedUse: 'Internal Bathroom & Kitchen Concealed Lines',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_plm_2',
    category: 'Plumbing',
    brand: 'Astral Pipes',
    productName: 'ProFit Multilayer Composite Hot & Cold Piping System',
    qualityLevel: 'Standard',
    approxPrice: 95,
    unit: 'per running ft',
    durability: '25+ Years',
    description: 'Zero-corrosion cross-linked polyethylene composite piping with press-fit brass fittings.',
    recommendedUse: 'Long-life Concealed Wet Wall Shafts',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_plm_3',
    category: 'Plumbing',
    brand: 'Geberit / Viega (Germany)',
    productName: 'Silent-PP Acoustic Soundproof Drainage & Press Fittings',
    qualityLevel: 'Premium',
    approxPrice: 220,
    unit: 'per running ft',
    durability: '40+ Years',
    description: 'Three-layer sound-damped mineral-reinforced polypropylene pipes ensuring zero water flow noise in bedroom walls.',
    recommendedUse: 'Multi-Storey Villa Vertical Plumbing Shafts',
  },

  // HARDWARE
  {
    id: 'mat_hrd_1',
    category: 'Hardware',
    brand: 'Godrej',
    productName: 'Mortise Locksets & Stainless Steel Ball Bearing Hinges',
    qualityLevel: 'Economy',
    approxPrice: 1800,
    unit: 'per door hardware kit',
    durability: '10 Years',
    description: 'High-security 6-lever brass tumbler mortise locks with SS304 grade hinges.',
    recommendedUse: 'Internal Bedrooms & Utility Doors',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_hrd_2',
    category: 'Hardware',
    brand: 'Hafele / Yale',
    productName: 'Architectural Concealed 3D Adjustable Hinges & Magnetic Locks',
    qualityLevel: 'Standard',
    approxPrice: 5200,
    unit: 'per door hardware kit',
    durability: '20 Years',
    description: 'Concealed invisible hinges with silent magnetic latch locks and sleek satin nickel levers.',
    recommendedUse: 'Designer Doors & Master Suites',
    isBudgetRecommended: true,
  },
  {
    id: 'mat_hrd_3',
    category: 'Hardware',
    brand: 'Sugatsune (Japan) / Olivari (Italy)',
    productName: 'Forged Solid Brass Designer Handles with Biometric Smart Entry',
    qualityLevel: 'Premium',
    approxPrice: 18500,
    unit: 'per door set',
    durability: '30+ Years',
    description: 'Handcrafted Italian solid forged brass door hardware with PVD titanium gold finish and concealed biometric recognition.',
    recommendedUse: 'Main Entrance & Luxury Bedroom Suites',
  }
];
